CREATE TABLE Couple_user
(
    exp_id SERIAL PRIMARY KEY,
	dest_id SERIAL PRIMARY KEY
);

CREATE TABLE Message
(
	msg_id SERIAL PRIMARY KEY,
	content VARCHAR(250)
);

CREATE TABLE Conversation
(
	exp_id SERIAL REFERENCES Couple_user(exp_id) ON DELETE CASCADE ON UPDATE CASCADE,
    dest_id SERIAL REFERENCES Couple_user(dest_id) ON DELETE CASCADE ON UPDATE CASCADE,
	msg_id VARCHAR(250) REFERENCES Message(msg_id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (exp_id, dest_id, msg_id)
);