//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!
package Interface ;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;

import javax.swing.*;
import javax.swing.event.*;

import Network.ClientHandler;
import Network.Server;

public class MainWindow extends JPanel implements ActionListener {
	private static ArrayList<ClientHandler> clients;
	private JButton refreshButton;
	private JButton disconnectButton;
	private JButton chatButton;
	private JTextArea TextAreaMain;
	private JTextField TextFieldMain;
	private JButton SendButton;
	private JLabel Label;
	public static JFrame mainFrame;
	private JPanel mainPanel;
	public static String query;
	private JComboBox<String> UsersList = null;
	private String username;

	public MainWindow(String username, ArrayList<ClientHandler> clients) {
		this.clients=clients;
		this.username=username;
		String[] init = {};
		UsersList = new JComboBox<String>(init);
		mainFrame = new JFrame (username);
		mainFrame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
		mainPanel = new JPanel(new GridLayout(10,10));

		TextAreaMain = new JTextArea (5, 5);
		TextFieldMain = new JTextField (5);
		Label = new JLabel ("GROUP CHAT");
		refreshButton = new JButton ("Refresh list");
		disconnectButton = new JButton ("Disconnect");
		chatButton = new JButton ("Chat");
		SendButton = new JButton ("Send");
		refreshButton.addActionListener(this);
		disconnectButton.addActionListener(this);
		chatButton.addActionListener(this);
		SendButton.addActionListener(this);

		refreshButton.setBounds (350, 20, 130, 25);
		disconnectButton.setBounds (350, 250, 130, 25);
		chatButton.setBounds (350, 105, 130, 25);
		UsersList.setBounds (350, 60, 130, 25);
		TextAreaMain.setBounds (20, 60, 310, 215);
		TextFieldMain.setBounds (20, 295, 310, 25);
		SendButton.setBounds (350, 295, 130, 25);
		Label.setBounds (135, 25, 80, 25);

		mainFrame.add (refreshButton);
		mainFrame.add (disconnectButton);
		mainFrame.add (chatButton);
		mainFrame.add (UsersList);
		mainFrame.add (TextAreaMain);
		mainFrame.add (TextFieldMain);
		mainFrame.add (SendButton);
		mainFrame.add (Label);

		mainFrame.setSize(new Dimension(2000, 500));
		mainFrame.getContentPane().add (mainPanel, BorderLayout.CENTER);
		mainFrame.pack();
		mainFrame.setSize(500,400);
		mainFrame.setVisible (true);


	}

	public static void main(String [] argv) {
		//		MainWindow mainWindow = new MainWindow(username);

	}

	@Override
	public void actionPerformed(ActionEvent e) {

		if(e.getSource() == disconnectButton) {
			query="disconnect";
			try {
				Thread.sleep(50);
			} catch (InterruptedException e1){e1.printStackTrace();
			}
			query=null;
		}

		if(e.getSource() == refreshButton) {
			
			
			
			
//			System.out.println("Refresh button clicked. Clients : ");
			try {
				Thread.sleep(2000); //to give time for the client handler thread to assign the username
			} catch (InterruptedException e1){e1.printStackTrace();}
//			System.out.println("MainWindow "+Server.getClients().size());
			for (ClientHandler client : Server.getClients()){
				if (client.getClientUsername()!=username) {
					UsersList.addItem(client.getClientUsername());
				}
			}
			String[] init = {};
			UsersList = new JComboBox<String>(init);
		}

	}
}


